#!/usr/bin/env node
/**
 * Renders the JSON that `k6 run --summary-export` leaves in `loadtest/results/`
 * into a Markdown table, so a run's numbers can be regenerated and pasted into a
 * report instead of transcribed by hand.
 *
 * Usage:
 *   node loadtest/report.mjs                       # both files, Markdown to stdout
 *   node loadtest/report.mjs --out results/REPORT.md
 *
 * Zero dependencies and plain ESM (`.mjs`), so it neither adds a package nor takes
 * part in the TypeScript build: the harness stays outside the application.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const RESULTS = resolve(HERE, 'results');

const MS = (value) => (typeof value === 'number' ? `${value.toFixed(2)} ms` : '—');
const PCT = (value) => (typeof value === 'number' ? `${(value * 100).toFixed(2)}%` : '—');

/** In k6's summary export a threshold entry is `true` when it was BREACHED. */
function verdict(thresholds) {
  if (!thresholds) return '—';
  const entries = Object.entries(thresholds);
  if (entries.length === 0) return '—';
  const breached = entries.filter(([, wasBreached]) => wasBreached === true);
  const names = entries.map(([name]) => name).join(', ');
  return breached.length === 0 ? `PASS (${names})` : `FAIL (${names})`;
}

function load(name) {
  const path = resolve(RESULTS, name);
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, 'utf8'));
}

function scenarioRows(metrics) {
  const rows = [];
  for (const [key, metric] of Object.entries(metrics)) {
    const match = /^http_req_duration\{scenario:(.+)\}$/.exec(key);
    if (!match) continue;
    rows.push({
      scenario: match[1],
      avg: metric.avg,
      med: metric.med,
      p90: metric['p(90)'],
      p95: metric['p(95)'],
      p99: metric['p(99)'],
      max: metric.max,
      verdict: verdict(metric.thresholds),
    });
  }
  return rows.sort((a, b) => a.scenario.localeCompare(b.scenario));
}

/**
 * `passes`/`fails` count the true/false observations of a Rate metric, so their
 * meaning flips with the metric: for `checks` a "pass" is a check that held, while
 * for `http_req_failed` a "pass" is a request that FAILED. Both are read that way.
 */
function totals(metrics) {
  const reqs = metrics.http_reqs || {};
  const failed = metrics.http_req_failed || {};
  const checks = metrics.checks || {};
  const failures = failed.passes ?? 0;
  const requests = failures + (failed.fails ?? 0);
  const checksRun = (checks.passes ?? 0) + (checks.fails ?? 0);
  return [
    ['Requests', (reqs.count ?? 0).toLocaleString('en-US')],
    ['Throughput', `${(reqs.rate ?? 0).toFixed(0)} req/s`],
    [
      'Failed requests',
      `${PCT(failed.value ?? failed.rate)} (${failures.toLocaleString('en-US')} of ${requests.toLocaleString('en-US')})`,
    ],
    [
      'Checks passed',
      `${PCT(checks.value ?? checks.rate)} (${(checks.passes ?? 0).toLocaleString('en-US')} of ${checksRun.toLocaleString('en-US')})`,
    ],
  ];
}

function table(headers, rows) {
  const head = `| ${headers.join(' | ')} |`;
  const rule = `|${headers.map(() => '---').join('|')}|`;
  const body = rows.map((row) => `| ${row.join(' | ')} |`).join('\n');
  return `${head}\n${rule}\n${body}`;
}

function renderRun(title, summary) {
  if (!summary) return `### ${title}\n\n_No summary found._\n`;
  const metrics = summary.metrics || {};
  const rows = scenarioRows(metrics);
  const parts = [`### ${title}`, '', table(['Metric', 'Value'], totals(metrics)), ''];

  if (rows.length > 0) {
    parts.push(
      table(
        ['Scenario', 'avg', 'median', 'p90', 'p95', 'p99', 'max', 'Threshold'],
        rows.map((r) => [
          `\`${r.scenario}\``,
          MS(r.avg),
          MS(r.med),
          MS(r.p90),
          MS(r.p95),
          MS(r.p99),
          MS(r.max),
          r.verdict,
        ]),
      ),
      '',
    );
  } else {
    const d = metrics.http_req_duration || {};
    parts.push(
      table(
        ['avg', 'median', 'p90', 'p95', 'p99', 'max'],
        [[MS(d.avg), MS(d.med), MS(d['p(90)']), MS(d['p(95)']), MS(d['p(99)']), MS(d.max)]],
      ),
      '',
    );
  }
  return parts.join('\n');
}

const markdown = [
  '<!-- Generated by `node loadtest/report.mjs` — do not edit by hand. -->',
  '# Load-test results',
  '',
  renderRun('Local battery (`loadtest/battery.js`)', load('battery.json')),
  renderRun('Production smoke (`loadtest/smoke.js`)', load('smoke.json')),
].join('\n');

const outFlag = process.argv.indexOf('--out');
if (outFlag !== -1 && process.argv[outFlag + 1]) {
  const target = resolve(process.cwd(), process.argv[outFlag + 1]);
  writeFileSync(target, `${markdown}\n`, 'utf8');
  process.stdout.write(`Report written to ${target}\n`);
} else {
  process.stdout.write(`${markdown}\n`);
}
